baseURL: 'http://localhost:1313/'

defaultContentLanguage: es
languageCode: es-mx
title: 'eyvot | Blog'
theme: PaperMod
paginate: 5
hrefTargetBlank: true
enableRobotsTXT: true

taxonomies:
  categoria: categorias
  etiqueta: etiquetas
  historial: historial
  informacion: informacion

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "eyvot | Blog"
  description: "Uno de mis rincones de internet, donde comparto parte de mis conocimientos o alguna que otra anécdota personal."
  keywords: ["blog", "eyvot blog", "eyvot", "blog de eyvot", "Fabián Leyva", "Fabián", "Leyva"]
  author: eyvot
  # author: ["Me", "You"] # multiple authors
  images: ["img/eyvot-blog-home.png"]
  DateFormat: "02-01-2006" # dd-mm-aaaa
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShareButtons: ['linkedin', 'whatsapp', 'telegram', 'twitter', 'facebook']

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  hideSummary: false
  comments: false
  hidemeta: false
  UseHugoToc: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
    # disableFingerprinting: true
    favicon: "img/favicon/favicon-48x48.png"
    favicon16x16: "img/favicon/favicon-16x16.png"
    favicon32x32: "img/favicon/favicon-32x32.png"
    favicon48x48: "img/favicon/favicon-48x48.png"
    favicon96x96: "img/favicon/favicon-96x96.png"
    favicon128x128: "img/favicon/favicon-128x128.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Inicio"
    icon: img/logo.svg
    iconHeight: 64

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "@eyvot"
    subtitle: "Blog"
    imageUrl: "img/profile-picture.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile picture

  # home-info mode
  homeInfoParams:
    Title: "Bienvenid@!"
    Content: Mis platillos llevan solo 2 ingredientes, pero los cocino de forma diferente.
    
  infoSocialIconsEyvot:
    - name: instagram
      url: "https://instagram.com/eyvot"
    - name: youtube
      url: "https://www.youtube.com/@eyvot"
    - name: twitter
      url: "https://twitter.com/eyvot"
    - name: linkedin
      url: "https://linkedin.com/in/eyvot"
    
  infoSocialIconsEyvotCodes:
    - name: github
      url: "https://github.com/eyvotCodes"
    - name: gitlab
      url: "https://gitlab.com/eyvotCodes"
    - name: youtube
      url: "https://www.youtube.com/@eyvotCodes"
  
  infoSocialIconsEyvotGames:
    - name: tiktok
      url: "https://www.tiktok.com/@eyvotGames"
    - name: instagram
      url: "https://www.instagram.com/eyvotGames"
    - name: youtube
      url: "https://www.youtube.com/@eyvotGames"
    - name: facebook
      url: "https://www.facebook.com/eyvotGames"

  analytics:
    google:
      SiteVerificationTag: ""
    bing:
      SiteVerificationTag: ""
    yandex:
      SiteVerificationTag: ""

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# menu:
#   main:
#     - identifier: categorias
#       name: 'Categorías'
#       url: /categorias/ 
#       weight: 20
#     - identifier: etiquetas
#       name: 'Etiquetas'
#       url: /etiquetas/
#       weight: 30
#     - identifier: historial
#       name: 'Historial'
#       url: /historial/
#       weight: 40
#     - identifier: informacion
#       name: 'Información'
#       url: /informacion/
#       weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: monokai
